automation:
  - id: e18beec6-b22c-4ac5-88da-05b7c05b9c33
    alias: "ECU reset with switch"
    triggers:
      - alias: "Solar energy output sensor not responding for 5 minutes"
        trigger: state
        entity_id: sensor.solar_total_lifetime_energy_output
        to:
          - unavailable
          - unknown
        for:
          minutes: 5
        id: "reset"
      - alias: ECU reports lower value then current return to grid
        trigger: template
        value_template: >
          {{
            states('sensor.ecu_current_power') | float(0) <
            states('sensor.electricity_meter_energieproductie') | float(0)
          }}
        for:
          minutes: 5
        id: "reset"
      - alias: "ECU current power didn't change for 15 minutes"
        trigger: state
        entity_id: sensor.ecu_current_power
        to: ~
        for:
          minutes: 5
        id: stable
      - alias: "Check every 10 minutes"
        trigger: time_pattern
        minutes: "/10"
        id: "check"
    conditions:
      - condition: or
        conditions:
          - condition: trigger
            id: reset
          - condition: and
            conditions:
              - condition: trigger
                id: stable
              - condition: state
                entity_id: sun.sun
                state: above_horizon
          - condition: and
            conditions:
              - condition: trigger
                id: check
              - condition: state
                entity_id: sensor.solar_total_lifetime_energy_output
                state:
                  - unavailable
                  - unknown
    actions:
      - alias: "Turn ECU reset switch off"
        action: switch.turn_off
        target:
          entity_id: switch.ecu_reset
      - alias: Wait for 10 seconds
        delay: 10
      - alias: "Turn ECU reset switch on"
        action: switch.turn_on
        target:
          entity_id: switch.ecu_reset
      - alias: Wait for 10 seconds
        delay: 10
      - alias: reload config entry
        action: homeassistant.reload_config_entry
        data:
          entry_id: 01JPJ2RR8DN5PF28SJWXPVHCN4
