# wasmachine_notificaties.yaml
automation:
  - id: 991bfa0a-ba49-462b-b78a-2aed72317903
    alias: "Notifications washing machine when done"
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: event.received
        target:
          entity_id: event.wasmachine_notification
        options:
          event_type:
            - washing_is_complete
        id: start
    actions:
      - alias: "Notification to phones"
        action: notify.all_phones
        data:
          title: "💦 Wasmachine is klaar"
          message: "Haal snel de was er uit voordat het allemaal kreukt."
          data:
            channel: Washing machine
            notification_icon: mdi:washing-machine
      - alias: Increase wash counter
        action: counter.increment
        target:
          entity_id: counter.aantal_wassen

  - id: 79338e3c-d3f9-4634-a4cb-a26050b684a4
    alias: "Notifications washing machine on error"
    mode: single
    max_exceeded: silent
    triggers:
      - trigger: state
        entity_id: event.wasmachine_error
        not_from:
          - unavailable
    actions:
      - alias: "Notification to phones"
        action: notify.all_phones
        data:
          title: "🛑 Wasmachine is heeft een error"
          message: "Wasmachine geeft de fout: {{ state_attr('event.wasmachine_error', 'event_type')}}"
          data:
            channel: Washing machine
            notification_icon: mdi:washing-machine
