automation:
  - id: e3bdd01c-27c4-4212-8747-3f84fa70701f
    alias: "Actions with smart buttons"
    mode: parallel
    max_exceeded: silent
    triggers:
      - alias: Trigger on button press event entity
        trigger: state
        entity_id:
          - event.knop_bed_floris_action
          - event.knop_bed_pepijn_action
        not_from: unavailable
    variables:
      event: "{{ trigger.to_state.attributes.event_type | default('unknown', true) }}"
      area: "{{ area_id(trigger.entity_id) }}"
    actions:
      - choose:
          - conditions: "{{ event == 'single' }}"
            sequence:
              - action: light.toggle
                target:
                  entity_id: >
                    {{
                      area_entities(area)
                        | select('in', label_entities('off_long_press'))
                        | select('in', label_entities('main_light'))
                        | list
                    }}
          - conditions: "{{ event == 'double' }}"
            sequence:
              - action: light.toggle
                target:
                  entity_id: >
                    {{
                      area_entities(area)
                        | select('in', label_entities('off_long_press'))
                        | select('in', label_entities('main_light'))
                        | list
                    }}
                data:
                  brightness: 255
          - conditions: "{{ event == 'hold' }}"
            sequence:
              - action: light.turn_off
                target:
                  entity_id: >
                    {{
                      area_entities(area)
                        | select('in', label_entities('off_long_press'))
                        | select('is_state', 'on')
                        | list
                    }}
